### ISSUE TITLE
TypeError on some client machines

### ISSUE THREAD

**Issue by ScottEvil** [ROGUE-JCTD/rogue-cookbook#29]
Using Mac OS-X Mavericks with Firefox and Chrome browser on a corporate built laptop. Adding a layer to the map throws the following error:

The following script error has occurred: "TypeError: Cannot read property 'success' of undefined". It is recommended that you reload the web page to resolve any potential complications.

**Comment by garnertb** [comment]
I now disable this by default in the build (per b39c2feacb4ec752a80da483b5085d324e6729c5).  Closing.
